sources:
  root: data/

  extensions:
    - mp4
    - ogv
    - webm
    - avi

repr:
  directory: data/representations
  storage_type: detect

processing:
  frame_sampling: 1
  save_frames: true
  match_distance: 0.75
  video_list_filename: video_dataset_list.txt
  filter_dark_videos: true
  filter_dark_videos_thr: 2
  min_video_duration_seconds: 3
  detect_scenes: true
  minimum_scene_duration: 2
  pretrained_model_local_path: null
  keep_fileoutput: true

database:
  use: false
  uri: postgres://postgres:admin@postgres:5432/videodeduplicationdb

templates:
  source_path: data/templates/test-group/CCSI Object Recognition External/
