name: winnow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - numpy
  - matplotlib
  - pandas
  - scikit-learn==0.23.2
  - scipy
  - tensorflow==1.15
  - tqdm
  - sqlalchemy
  - psycopg2
  - pytest
  - jupyter
  - jupyterlab
  - pysoundfile
  - h5py==2.9.0
  - ffmpeg
  - pip
  - pip:
      - lmdb
      - image
      - imageio
      - moviepy
      - opencv-contrib-python
      - pillow
      - scenedetect
      - pyyaml
      - cached-property
      - dataclasses
      - celery==5.0.5
      - redis
      - billiard
      - librosa
      - fire
      - inquirer
      - pytimeparse
      - annoy
      - yt-dlp
      - dacite
      - deprecation
      - torch

prefix: C:\ProgramData\Anaconda3\envs\winnow
