name: winnow
channels:
  - pytorch-nightly
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - cuml
  - cudatoolkit==11.4
  - numpy==1.21.5
  - matplotlib==3.5.1
  - pandas  
  - scikit-learn
  - scipy==1.8.0 
  - tqdm
  - sqlalchemy
  - psycopg2
  - pytest
  - jupyter
  - jupyterlab
  - pysoundfile
  - h5py==3.6.0
  - ffmpeg==5.0.0
  - numba
  - pynndescent
  - luigi
  - tabulate
  - umap-learn
  - networkit
  - pip==22.0.4
  - pip:
      - lmdb
      - image==1.5.33
      - imageio==2.16.1
      - moviepy
      - opencv-contrib-python
      - pillow
      - scenedetect
      - pyyaml==6.0
      - cached-property
      - dataclasses
      - celery==5.2.3
      - redis
      - billiard
      - librosa
      - fire
      - inquirer
      - pytimeparse
      - annoy==1.17
      - yt-dlp
      - dacite==1.6.0
      - deprecation
      - grpcio==1.44
      - grpcio-tools==1.44
      - tf-slim==1.1
      - tensorflow==2.8
      - torch==1.11
      - trimap
      - pacmap
      - typing_extensions==4.1.1
      
