name: winnow
channels:
  - conda-forge
  - defaults
dependencies:
  - gnutls=3.6.5=ha0399c4_1
  - matplotlib-base=3.0.2=py36h20b835b_1
  - nettle=3.4.1=h470a237_2
  - openh264=1.8.0=hd28b015_0
  - x264=1!152.20180717=h470a237_1
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.0=py36_0
  - astor=0.7.1=py36_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py36_0
  - blas=1.0=openblas
  - bleach=3.1.0=py36_0
  - bzip2=1.0.6=h14c3975_5
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.1.23=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.3.9=py36_0
  - cudatoolkit=9.2=0
  - cudnn=7.3.1=cuda9.2_0
  - cupti=9.2.148=0
  - cycler=0.10.0=py36_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.3.2=py36_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - giflib=5.1.4=h14c3975_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.3.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.2=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.13.3=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - jupyterlab=0.35.4=py36hf63ae98_0
  - jupyterlab_server=0.2.0=py36_0
  - keras=2.2.4=0
  - keras-applications=1.0.6=py36_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.15=h63c8f33_5
  - libopenblas=0.3.3=h5a2b251_3
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.0.1=h8e7db2f_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markdown=3.0.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.0.2=py36h5429711_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.1=144
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - nomkl=3.0=0
  - notebook=5.7.6=py36_0
  - numpy=1.16.2=py36h99e49ec_0
  - numpy-base=1.16.2=py36h2f8d375_0
  - openblas=0.3.3=3
  - openblas-devel=0.3.3=3
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1b=h7b6447c_1
  - pandas=0.24.1=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.4=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=19.0.3=py36_0
  - pixman=0.36.0=h7b6447c_0
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.6.1=py36he6710b0_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pygments=2.3.1=py36_0
  - pyparsing=2.3.1=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.14.11=py36h7b6447c_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2018.9=py36_0
  - pyyaml=3.13=py36h14c3975_0
  - pyzmq=18.0.0=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.4.3=py36_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.2=py36h22eb022_0
  - scipy=1.2.1=py36he2b7bc3_0
  - send2trash=1.5.0=py36_0
  - setuptools=40.8.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.26.0=h7b6447c_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he74679b_0
  - tensorflow-base=1.12.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py36h7b6447c_0
  - tqdm=4.31.1=py_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.33.1=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - chardet==3.0.4
    - click==7.0
    - django==2.1.5
    - idna==2.8
    - image==1.5.27
    - imageio==2.4.1
    - moviepy==0.2.3.5
    - networkx==2.2
    - opencv-python==4.0.0.21
    - pillow==5.4.1
    - pyvis==0.1.5.0
    - requests==2.21.0
    - scenedetect==0.5
    - simplegeneric==0.8.1
    - urllib3==1.24.1
    - winnow==0.1.0
    - xlrd==1.2.0
prefix: /home/felipeb/.conda/envs/winnow

