name: Server CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./server
        run: |
          python -m pip install --upgrade pip
          pip install flake8 'black~=20.8b1'
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Check formatting with black
        working-directory: ./server
        run: |
          # Check formatting of the server package and tests
          black --line-length 120 --check server tests
      - name: Lint with flake8
        working-directory: ./server
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # --ignore=E203 as it is not PEP8 and black style compliant. See: https://github.com/psf/black/issues/315
          flake8 . --count --max-complexity=10 --ignore=E203 --max-line-length=127 --statistics
      - name: Test with pytest
        working-directory: ./server
        run: |
          export PYTHONPATH="$(pwd)"
          pytest