name: Frontend CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        working-directory: ./web
      - name: Build
        run: npm run build
        working-directory: ./web
      - name: Test
        run: npm test
        working-directory: ./web
      - name: Prepare E2E Testing
        working-directory: ./web
        run: npm run cy:server
      - name: E2E Testing with Cypress on Firefox
        working-directory: ./web
        run: npm run cy:firefox
      - name: Archive Cypress Firefox screenshots if failed
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: cypress-firefox-screenshots
          path: web/e2e/cypress/screenshots/**/*.png
      - name: E2E Testing with Cypress on Chrome
        working-directory: ./web
        run: npm run cy:chrome
      - name: Archive Cypress Chrome screenshots if failed
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: cypress-chrome-screenshots
          path: web/e2e/cypress/screenshots/**/*.png
